### ISSUE TITLE
LayoutNode should be attached to an owner

### ISSUE THREAD

**Issue by omarzer0** [anastr/Speedometer#2]
When I navigate back from a screen that uses this Speedometer Composable it sometimes throws this exception.

Some Info:
- KMP project
- Navigation with Decompose + Router
-  kotlin = "1.9.10"
- agp = "8.1.2"
- compose = "1.5.1"

```
PID: 6165
java.lang.IllegalStateException: LayoutNode should be attached to an owner
    at androidx.compose.ui.node.LayoutNodeKt.requireOwner(LayoutNode.kt:1448)
    at androidx.compose.ui.node.LayoutNode.invalidateSemantics$ui_release(LayoutNode.kt:412)
    at androidx.compose.ui.node.SemanticsModifierNodeKt.invalidateSemantics(SemanticsModifierNode.kt:92)
    at androidx.compose.foundation.text.modifiers.TextAnnotatedStringNode.doInvalidations(TextAnnotatedStringNode.kt:210)
    at androidx.compose.foundation.text.modifiers.TextAnnotatedStringElement.update(TextAnnotatedStringElement.kt:67)
    at androidx.compose.foundation.text.modifiers.TextAnnotatedStringElement.update(TextAnnotatedStringElement.kt:36)
    at androidx.compose.ui.node.NodeChainKt.updateUnsafe(NodeChain.kt:808)
    at androidx.compose.ui.node.NodeChainKt.access$updateUnsafe(NodeChain.kt:1)
    at androidx.compose.ui.node.NodeChain.updateNode(NodeChain.kt:653)
    at androidx.compose.ui.node.NodeChain.updateFrom$ui_release(NodeChain.kt:138)
    at androidx.compose.ui.node.LayoutNode.setModifier(LayoutNode.kt:844)
    at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:47)
    at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:47)
    at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1712)
    at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1710)
    at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
    at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
    at android.view.Choreographer.doFrame(Choreographer.java:1040)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8030)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@fffc223, androidx.compose.ui.platform.MotionDurationScaleImpl@71e8320, StandaloneCoroutine{Cancelling}@eb1c4d9, AndroidUiDispatcher@4811e9e]

```

**Comment by omarzer0** [comment]
The error was not actually related to the Speedometer but rather updating it incorrectly results in this crash.
